import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { Brain, FileText, Sparkles, Download, AlertTriangle, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import html2pdf from 'html2pdf.js';

const API_URL = import.meta.env.VITE_API_URL || 'https://ai-research-assistant-2zmw.onrender.com';

export default function SharedReport() {
  const { slug } = useParams();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const res = await fetch(`${API_URL}/api/public/${slug}`);
        if (!res.ok) throw new Error('Report not found or no longer public.');
        setData(await res.json());
      } catch (e) {
        setError(e.message);
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
  }, [slug]);

  const downloadPdf = () => {
    const element = document.getElementById('report-content');
    const style = document.createElement('style');
    style.innerHTML = `
      #report-content, #report-content * { color: #000 !important; background: #fff !important; }
      #report-content h1, #report-content h2, #report-content h3 { page-break-after: avoid !important; break-after: avoid !important; }
      #report-content p, #report-content li { page-break-inside: avoid !important; break-inside: avoid !important; }
    `;
    document.head.appendChild(style);
    html2pdf().set({
      margin: 0.5,
      filename: `Research_${data.topic.replace(/\s+/g, '_')}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' },
      pagebreak: { mode: ['css', 'legacy'], avoid: ['p', 'h1', 'h2', 'h3', 'h4', 'li'] }
    }).from(element).save().then(() => document.head.removeChild(style));
  };

  const MarkdownComponents = {
    a: ({ node, ...props }) => {
      let href = props.href || '';
      if (href && !/^https?:\/\//i.test(href)) href = `https://${href}`;
      return <a {...props} href={href} target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent-primary)', textDecoration: 'underline' }} />;
    }
  };

  return (
    <div style={{ minHeight: '100vh', paddingTop: '80px', paddingBottom: '60px' }}>
      <div style={{ maxWidth: '900px', margin: '0 auto', padding: '0 1.5rem' }}>

        {loading && (
          <div style={{ textAlign: 'center', padding: '5rem 0' }}>
            <Loader2 size={40} className="animate-spin" color="var(--accent-primary)" style={{ margin: '0 auto 1rem' }} />
            <p style={{ color: 'var(--text-secondary)' }}>Loading shared report...</p>
          </div>
        )}

        {error && (
          <div style={{ textAlign: 'center', padding: '5rem 0' }}>
            <AlertTriangle size={48} color="#f87171" style={{ margin: '0 auto 1rem' }} />
            <h2 style={{ marginBottom: '0.5rem' }}>Report Not Found</h2>
            <p style={{ color: 'var(--text-secondary)' }}>{error}</p>
          </div>
        )}

        {data && (
          <div className="animate-fade-in">
            {/* Banner */}
            <div style={{ padding: '0.75rem 1.25rem', borderRadius: '0.75rem', background: 'rgba(139,92,246,0.1)', border: '1px solid rgba(139,92,246,0.25)', marginBottom: '2rem', display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
              <Sparkles size={16} color="var(--accent-primary)" />
              <span style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
                This is a publicly shared research report generated by <strong style={{ color: 'var(--accent-primary)' }}>NexusAI</strong>.
              </span>
            </div>

            {/* Title Row */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
              <h1 style={{ fontSize: 'clamp(1.3rem, 3vw, 1.8rem)', margin: 0 }}>
                <span className="text-gradient">{data.topic}</span>
              </h1>
              <button onClick={downloadPdf} className="btn btn-outline" style={{ padding: '0.5rem 1rem', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <Download size={16} /> Download PDF
              </button>
            </div>

            {/* Report */}
            <div id="report-content" className="glass-panel" style={{ padding: 'clamp(1.25rem, 4vw, 2rem)', borderRadius: '1rem', marginBottom: '1.5rem', background: 'var(--bg-secondary)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1.25rem', paddingBottom: '1rem', borderBottom: '1px solid var(--border-subtle)' }}>
                <FileText size={20} color="var(--accent-primary)" />
                <h2 style={{ color: 'var(--accent-primary)', margin: 0, fontSize: '1.1rem' }}>Deep Research Report</h2>
              </div>
              <div className="markdown-content" style={{ color: 'var(--text-primary)', lineHeight: 1.8 }}>
                <ReactMarkdown components={MarkdownComponents}>{data.report}</ReactMarkdown>
              </div>
            </div>

            {/* Critic */}
            {data.feedback && (
              <div className="glass-panel" style={{ padding: 'clamp(1.25rem, 4vw, 2rem)', borderRadius: '1rem', border: '1px solid rgba(168,85,247,0.3)', marginBottom: '2rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1.25rem', paddingBottom: '1rem', borderBottom: '1px solid var(--border-subtle)' }}>
                  <Brain size={20} color="var(--accent-secondary)" />
                  <h2 style={{ color: 'var(--accent-secondary)', margin: 0, fontSize: '1.1rem' }}>Critic Review</h2>
                </div>
                <div className="markdown-content" style={{ color: 'var(--text-secondary)', lineHeight: 1.8 }}>
                  <ReactMarkdown components={MarkdownComponents}>{data.feedback}</ReactMarkdown>
                </div>
              </div>
            )}

            {/* Footer CTA */}
            <div className="glass-panel" style={{ padding: '1.5rem', borderRadius: '1rem', textAlign: 'center' }}>
              <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem', fontSize: '0.95rem' }}>
                Want to generate your own deep research reports?
              </p>
              <a href="/" className="btn btn-primary" style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', textDecoration: 'none' }}>
                <Sparkles size={16} /> Try NexusAI for free
              </a>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
